name: Update streak stats

on:
  schedule:
    - cron: "0 * * * *"   # toutes les heures
  push:
    paths:
      - ".github/workflows/streak-stats.yml"   # se relance si ce fichier est modifié
  workflow_dispatch:       # permet de le lancer manuellement

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Generate streak stats
        uses: DenverCoder1/github-readme-streak-stats@main
        with:
          options: user=hrasamoe&theme=tokyonight&hide_border=true
          path: assets/streak.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit streak stats
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add assets/streak.svg
          git commit -m "Update streak stats" || exit 0
          git push
